name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
    - uses: actions/checkout@v2

    - name: Generate Version
      run: |-
        cat <<EOF > src/generated/version.json
        {
          "pepe":"genero versionX ok o no?",
          "version" : "$(echo ${GITHUB_REF:10})",  
          "tag": "$(git describe --tags)",
          "revision" : "$(git rev-list HEAD --count)",  
          "date" : "$(date --iso-8601=seconds)",
          "git_revision" : "$(git rev-parse --short HEAD)"
        }  

    - name: Build
      run: |
        npm install
        npm run build 

    - name: Test E2E
      run: | 
        npm run e2e

